---
- name: extract itop 
  unarchive: src=/usr/src/iTop-2.2.0-2459.zip dest=/var/www/{{ fqdn }} copy=no

- name: create necessary dirs
  file: name={{ item }} owner=root group=www-data mode=0775 state=directory recurse=yes
  with_items:
    - /var/www/{{ fqdn }}/web
    - /var/www/{{ fqdn }}/web/log
    - /var/www/{{ fqdn }}/web/env-production
    - /var/www/{{ fqdn }}/web/conf
    - /var/www/{{ fqdn }}/web/data

- name: extract toolkit 
  unarchive: src=/usr/src/iTopDataModelToolkit-2.2.zip dest=/var/www/{{ fqdn }}/web copy=no

- name: permissions on toolkit 
  file: name=/var/www/{{ fqdn }}/web/toolkit owner=root group=www-data mode=0775 state=directory recurse=yes

- name: extract teemip 
  unarchive: src=/usr/src/TeemIp-Module-2.0.2.zip dest=/var/www/{{ fqdn }}/web/extensions copy=no
  when: install_module and install_teemip

- name: verify if config-itop exists 
  stat: path=/var/www/{{ fqdn }}/web/conf/production/config-itop.php
  register: config_itop_vhost
  when: install_module

- name: add write to config-itop, to execute web/setup 
  file: path=/var/www/{{ fqdn }}/web/conf/production/config-itop.php mode="a+w"
  when: install_module and config_itop_vhost.stat.exists == True
