---
- name: download itop
  get_url: url=http://downloads.sourceforge.net/project/itop/itop/2.2.0/iTop-2.2.0-2459.zip dest=/usr/src/iTop-2.2.0-2459.zip

- name: download toolkit
  get_url: url=http://www.combodo.com/documentation/iTopDataModelToolkit-2.2.zip dest=/usr/src/iTopDataModelToolkit-2.2.zip

- name: download teemip module
  get_url: url=http://downloads.sourceforge.net/project/teemip/teemip%20-%20an%20iTop%20module/2.0.2/TeemIp-Module-2.0.2.zip dest=/usr/src/TeemIp-Module-2.0.2.zip
  when: install_module and install_teemip

- name: apache subrole vhost
  include: apache_vhost.yml
  when: vhost

- name: apache subrole vhost
  include: apache_novhost.yml
  when: vhost == False
