---
- name: download itop
  get_url: url=http://downloads.sourceforge.net/project/itop/itop/2.2.0/iTop-2.2.0-2459.zip dest=/usr/src/iTop-2.2.0-2459.zip

- name: extract itop to vhost
  unarchive: src=/usr/src/iTop-2.2.0-2459.zip dest=/var/www/{{ fqdn }}
  when: vhost

- name: extract itop
  unarchive: src=/usr/src/iTop-2.2.0-2459.zip dest=/var/www/html

- name: create necessary dirs to vhost
  file: name={{ item }} owner=root group=www-data mode=0775 state=directory recurse=yes
  with_items:
    - /var/www/{{ fqdn }}/web
    - /var/www/{{ fqdn }}/web/log
    - /var/www/{{ fqdn }}/web/env-production
    - /var/www/{{ fqdn }}/web/conf
    - /var/www/{{ fqdn }}/web/data
  when: vhost

- name: create necessary dirs
  file: name={{ item }} owner=root group=www-data mode=0775 state=directory recurse=yes
  with_items:
    - /var/www/html/web
    - /var/www/html/web/log
    - /var/www/html/web/env-production
    - /var/www/html/web/conf
    - /var/www/html/web/data

- name: download toolkit
  get_url: url=http://www.combodo.com/documentation/iTopDataModelToolkit-2.2.zip dest=/usr/src/iTopDataModelToolkit-2.2.zip

- name: extract toolkit to vhost
  unarchive: src=/usr/src/iTopDataModelToolkit-2.2.zip dest=/var/www/{{ fqdn }}/web
  when: vhost

- name: extract toolkit
  unarchive: src=/usr/src/iTopDataModelToolkit-2.2.zip dest=/var/www/html/web

- name: permissions on toolkit to vhost
  file: name=/var/www/{{ fqdn }}/web/toolkit owner=root group=www-data mode=0775 state=directory recurse=yes
  when: vhost

- name: permissions on toolkit
  file: name=/var/www/html/web/toolkit owner=root group=www-data mode=0775 state=directory recurse=yes

- name: download teemip module
  get_url: url=http://downloads.sourceforge.net/project/teemip/teemip%20-%20an%20iTop%20module/2.0.2/TeemIp-Module-2.0.2.zip dest=/usr/src/TeemIp-Module-2.0.2.zip
  when: install_module and install_teemip

- name: extract teemip to vhost
  unarchive: src=/usr/src/TeemIp-Module-2.0.2.zip dest=/var/www/{{ fqdn }}/web/extensions
  when: vhost and install_module and install_teemip

- name: extract teemip
  unarchive: src=/usr/src/TeemIp-Module-2.0.2.zip dest=/var/www/html/web/extensions
  when: install_module and install_teemip

- name: verify if config-itop exists to vhost
  stat: path=/var/www/{{ fqdn }}/web/conf/production/config-itop.php
  register: config_itop_vhost
  when: vhost and install_module

- name: verify if config-itop exists
  stat: path=/var/www/html/web/conf/production/config-itop.php
  register: config_itop
  when: install_module

- name: add write to config-itop, to execute web/setup to vhost
  file: path=/var/www/{{ fqdn }}/web/conf/production/config-itop.php mode="a+w"
  when: vhost and install_module and config_itop_vhost.stat.exists == True

- name: add write to config-itop, to execute web/setup
  file: path=/var/www/html/web/conf/production/config-itop.php mode="a+w"
  when: install_module and config_itop.stat.exists == True
